# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-17 13:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoPolaridade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frase', models.TextField()),
                ('polaridade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DatasetTreito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('fonte', models.CharField(max_length=30)),
                ('data', models.DateField()),
                ('arquivo', models.FileField(upload_to='media/dataset')),
                ('valido', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Extracao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instante', models.DateTimeField()),
                ('fonte', models.CharField(max_length=30)),
                ('termo', models.CharField(max_length=50)),
                ('concluido', models.BooleanField(default=False)),
                ('quantidade', models.IntegerField(default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Processamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('concluido', models.BooleanField(default=False)),
                ('extracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrm.Extracao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='avaliacaopolaridade',
            name='processamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrm.Processamento'),
        ),
    ]
