# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-17 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrm', '0003_auto_20170616_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='extracao',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
    ]
